const COLLECTION_GOALS = {
    Wheat: {formula: E => E / 3600, requirement: "garden1"}, 
    Carrot: {formula: E => E / 13371, requirement: "garden1"}, 
    Potato: {formula: E => E / 13371, requirement: "garden5"},
    Pumpkin: {formula: E => E / 3600, requirement: "garden5"},
    Melon: {formula: E => E / 18000, requirement: "garden5"},
    Mushroom: null,
    Cactus: null,
    "Sugar Cane": {formula: E => E / 7200, requirement: "garden5"},
    Feather: "Minion",
    "Raw Chicken": "Minion",
    Leather: "Minion",
    "Raw Porkchop": "Minion",
    Mutton: "Minion",
    "Raw Rabbit": "Minion",
    "Lapis Lazuli": {formula: E => E / 3442.5, requirement: "hotm3"},
    Cobblestone: {formula: E => E / 4500, requirement: "hotm3"},
    Coal: {formula: E => E / 2012.5, requirement: "hotm3"},
    "Iron Ingot": {formula: E => E / 1962.5, requirement: "hotm3"},
    "Gold Ingot": {formula: E => E / 2012.5, requirement: "hotm3"},
    Diamond: {formula: E => E / 1937.5, requirement: "hotm3"},
    Emerald: {formula: E => E / 1950, requirement: "hotm3"},
    Redstone: {formula: E => E / 3487.5, requirement: "hotm3"},
    "Cocoa Beans": null,
    Obsidian: {formula: E => E / 600, requirement: "combat15"},
    Gravel: {formula: E => E / 3800, requirement: "combat15"},
    Sand: {formula: E => E / 4500, requirement: "hotm3"},
    "End Stone": {formula: E => E / 4200, requirement: "combat15"},
    Mithril: null,
    "Hard Stone": null,
    Gemstone: null,
    "Rotten Flesh": null,
    Bone: null,
    String: null,
    "Spider Eye": null,
    Gunpowder: "Minion",
    "Ender Pearl": null,
    Slimeball: "Minion",
    "Oak Log": {formula: E => E / 1680, requirement: "hotf1"},
    "Birch Log": {formula: E => E / 2660, requirement: "hotf1"},
    "Spruce Log": {formula: E => E / 1824, requirement: "hotf1"},
    "Dark Oak Log": {formula: E => E / 4180, requirement: "hotf1"},
    "Acacia Log": {formula: E => E / 3610, requirement: "hotf1"},
    "Jungle Log": {formula: E => E / 4180, requirement: "hotf1"},
    "Raw Fish": "Minion",
    "Raw Salmon": "Minion",
    Clownfish: "Minion",
    Pufferfish: "Minion",
    "Prismarine Shard": "Minion",
    "Prismarine Crystals": "Minion",
    Sponge: "Minion",
    Clay: "Minion",
    "Lily Pad": null,
    "Ink Sac": null
}
