const COLLECTION_GOALS = {
    Wheat: {formula: E => E / 3600, requirement: "garden1"}, 
    Carrot: {formula: E => E / 13371, requirement: "garden1"}, 
    Potato: {formula: E => E / 13371, requirement: "garden5"},
    Pumpkin: {formula: E => E / 3600, requirement: "garden5"},
    "Melon Slice": {formula: E => E / 17999, requirement: "garden5"},
    Mushroom: null,
    Cactus: null,
    "Sugar Cane": {formula: E => E / 7200, requirement: "garden5"},
    Feather: "Minion",
    "Raw Chicken": "Minion",
    Leather: "Minion",
    "Raw Porkchop": "Minion",
    "Raw Mutton": "Minion",
    "Raw Rabbit": "Minion",
    "Lapis Lazuli": {formula: E => E / 2740.5, requirement: "hotm3"},
    Cobblestone: {formula: E => E / 4500, requirement: "hotm3"},
    Coal: {formula: E => E / 1622.5, requirement: "hotm3"},
    "Iron Ingot": {formula: E => E / 1572.5, requirement: "hotm3"},
    "Gold Ingot": {formula: E => E / 1622.5, requirement: "hotm3"},
    Diamond: {formula: E => E / 1547.5, requirement: "hotm3"},
    Emerald: {formula: E => E / 1560, requirement: "hotm3"},
    "Redstone Dust": {formula: E => E / 2785.5, requirement: "hotm3"},
    "Cocoa Beans": null,
    Obsidian: {formula: E => E / 540, requirement: "combat15"},
    Gravel: {formula: E => E / 3800, requirement: "combat15"},
    Sand: {formula: E => E / 4500, requirement: "hotm3"},
    "End Stone": {formula: E => E / 4050, requirement: "combat15"},
    Mithril: null,
    "Hard Stone": {formula: E => E / 7000, requirement: "hotm4"},
    Gemstone: {formula: E => E / 500, requirement: "hotm4"},
    "Rotten Flesh": "Minion",
    Bone: "Minion",
    String: "Minion",
    "Spider Eye": "Minion",
    Gunpowder: "Minion",
    "Ender Pearl": null,
    Slimeball: "Minion",
    "Oak Log": {formula: E => E / 1680, requirement: "hotf1"},
    "Birch Log": {formula: E => E / 2660, requirement: "hotf1"},
    "Spruce Log": {formula: E => E / 1824, requirement: "hotf1"},
    "Dark Oak Log": {formula: E => E / 4180, requirement: "hotf1"},
    "Acacia Log": {formula: E => E / 3610, requirement: "hotf1"},
    "Jungle Log": {formula: E => E / 4180, requirement: "hotf1"},
    "Raw Cod": "Minion",
    "Raw Salmon": "Minion",
    "Tropical Fish": "Minion",
    Pufferfish: "Minion",
    "Prismarine Shard": "Minion",
    "Prismarine Crystals": "Minion",
    Sponge: "Minion",
    "Clay Ball": "Minion",
    "Lily Pad": null,
    "Ink Sac": null
}
