const COLLECTION_GOALS = {
    Wheat: {formula: E => E / 3600, requirement: "garden1"}, 
    Carrot: {formula: E => E / 13371, requirement: "garden1"}, 
    Potato: {formula: E => E / 13371, requirement: "garden5"},
    Pumpkin: {formula: E => E / 3600, requirement: "garden5"},
    Melon: {formula: E => E / 18000, requirement: "garden5"},
    Mushroom: null,
    Cactus: null,
    "Sugar Cane": {formula: E => E / 7200, requirement: "garden5"},
    Feather: "Minion",
    "Raw Chicken": "Minion",
    Leather: "Minion",
    "Raw Porkchop": "Minion",
    Mutton: "Minion",
    "Raw Rabbit": "Minion",
    "Lapis Lazuli": {formula: E => E / 3442.5, requirement: "hotm3"},
    Cobblestone: {formula: E => E / 4500, requirement: "hotm3"},
    Coal: {formula: E => E / 2012.5, requirement: "hotm3"},
    "Iron Ingot": {formula: E => E / 1962.5, requirement: "hotm3"},
    "Gold Ingot": {formula: E => E / 2012.5, requirement: "hotm3"},
    Diamond: {formula: E => E / 1937.5, requirement: "hotm3"},
    Emerald: {formula: E => E / 1950, requirement: "hotm3"},
    Redstone: {formula: E => E / 3487.5, requirement: "hotm3"},
}
